StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65ECE7C2CC2DDBFE}" {
   Id "PRTC-Lore_Marker_BaseDefenders"
   Target_en_us "Base Defenders"
   Modified 1710027408
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2381502C5}" {
   Id "PRTC-Lore_Marker_Patrols"
   Target_en_us "Patrols"
   Modified 1710027434
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C0B1CDE958}" {
   Id "PRTC-Lore_MissionStatus_CaptureWarCriminal_Partial"
   Target_en_us "Congratulations, you have captured the war criminal."
   Modified 1710028150
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CB248EBFBC}" {
   Id "PRTC-Lore_MissionStatus_ProvideShelter_Defeat"
   Target_en_us "You were unable to provide shelter to enough civilians."
   Modified 1710030960
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CD43FA87E4}" {
   Id "PRTC-Lore_MissionStatus_ProvideShelter_Victory"
   Target_en_us "Congratulations, you have provided with shelter the civilians fleeing the fighting."
   Modified 1710029985
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C4A6EB1C67}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Defeat"
   Target_en_us "This is a disaster, no civilian was saved."
   Modified 1710026090
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C5CA899496}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Draw"
   Target_en_us "Unfortunately, you could only save some civilians."
   Modified 1710025781
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C5615B3F3A}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Partial"
   Target_en_us "Good job, you have saved many civilians."
   Modified 1710025963
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C54E5E38A9}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Victory"
   Target_en_us "Congratulations, you have saved most civilians!"
   Modified 1710026137
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C44EE48C32}" {
   Id "PRTC-Lore_Spawn_Approach"
   Target_en_us "Approach"
   Modified 1710026461
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C3E3A49FDB}" {
   Id "PRTC-Lore_Spawn_Bunker"
   Target_en_us "Bunker"
   Modified 1710026908
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2FF9661C9}" {
   Id "PRTC-Lore_Spawn_Hospital"
   Target_en_us "Hospital"
   Modified 1710027313
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C714DC30C3}" {
   Id "PRTC-Lore_Spawn_Hotel"
   Target_en_us "Hotel"
   Modified 1710024951
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C7315FE9C2}" {
   Id "PRTC-Lore_Spawn_Insertion"
   Target_en_us "Insertion"
   Modified 1710024904
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C3BD6C239C}" {
   Id "PRTC-Lore_Spawn_MainBuilding"
   Target_en_us "Main Building"
   Modified 1710026484
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC148705644}" {
   Id "PRTC-SC01_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This short mission showcases:"\
   ""\
   "- The automated population of houses with civilians."\
   ""\
   "- The \"protection\" of AI non-combattants via their recruitment to commanded groups."\
   ""\
   "- Two additional civilian factions (Rural and Urban Civilians), which can be used to model populations of mixed ethnicity, social background, etc."\
   ""\
   "As confusion and misunderstandings reign, you have to focus on your mission to protect specific persons, while doing your best to prevent any war crime."
   Modified 1708331764
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC154C46AF7}" {
   Id "PRTC-SC01_IntroHint_Title"
   Target_en_us "Protection - Showcase #1"
   Modified 1707943634
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC36AAFBB60}" {
   Id "PRTC-SC01_Task01_Text"
   Target_en_us "Take a car and drive fast to Arleville in order to join urban businessmen meeting with the rural mayor."
   Modified 1710025159
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC49CAA44F1}" {
   Id "PRTC-SC01_Task01_Title"
   Target_en_us "Drive To Arleville"
   Modified 1707943319
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C75859E049}" {
   Id "PRTC-SC01_Task02_Text"
   Target_en_us "Stay put and defend the businessmen until we understand what is going on."
   Modified 1710025133
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C77B207142}" {
   Id "PRTC-SC01_Task02_Title"
   Target_en_us "Defend The Businessmen"
   Modified 1710025027
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C61ECD1FDD}" {
   Id "PRTC-SC01_Task03_Text"
   Target_en_us "Enraged FIA soldiers are arriving to protect the rural civilians. Avoid them and extract the surviving businessmen to Beauregard."
   Modified 1710025531
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C6C389BC1E}" {
   Id "PRTC-SC01_Task03_Title"
   Target_en_us "Flee With A Vehicle To Beauregard"
   Modified 1710025363
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65F4A826D55DBC72}" {
   Id "PRTC-SC01_Text"
   Target_en_us "Tensions are escalating between the Rural and Urban communities on Arland, with the FIA clearly supporting the Rurals. As you join the US-provided security detail of Urban businessmen meeting the Rural mayor of Arleville, rogue Soviet forces are suddenly appearing on the small island..."
   Modified 1710537060
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65F4A826EAC4E339}" {
   Id "PRTC-SC01_Title"
   Target_en_us "Mayor's Meeting"
   Modified 1710537052
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65D2F2451AC8854B}" {
   Id "PRTC-SC02_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This more dynamic and complex mission showcases:"\
   ""\
   "- The \"protection\" of AI non-combattants via their recruitment to commanded groups, and the challenges with directing them under heavy fire."\
   ""\
   "- The capturing of unarmed enemies."\
   ""\
   "The goal is to save as many civilians as possible, unfortunately not all of them. You will probably have to leave some behind in order to save at least few..."
   Modified 1708331290
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65D2F25A955474FD}" {
   Id "PRTC-SC02_IntroHint_Title"
   Target_en_us "Protection - Showcase #2"
   Modified 1708331814
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C406FA72AC}" {
   Id "PRTC-SC02_TaskApproach_Text"
   Target_en_us "Approach the base from the south-east."
   Modified 1710026362
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C4146E51E1}" {
   Id "PRTC-SC02_TaskApproach_Title"
   Target_en_us "Approach"
   Modified 1710026342
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C38ED3660E}" {
   Id "PRTC-SC02_TaskBunker_Text"
   Target_en_us "Approach the bunker and try to free the prisoners inside."
   Modified 1710026831
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C398209E7F}" {
   Id "PRTC-SC02_TaskBunker_Title"
   Target_en_us "Approach Bunker"
   Modified 1710026807
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C1225D2B39}" {
   Id "PRTC-SC02_TaskExtraction_Text"
   Target_en_us "Bring the civilans and/or the war criminal to the extraction point."
   Modified 1710027956
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C1C042FE4B}" {
   Id "PRTC-SC02_TaskExtraction_Title"
   Target_en_us "Extraction"
   Modified 1710027881
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2A903EA07}" {
   Id "PRTC-SC02_TaskHospital_Text"
   Target_en_us "Approach the hospital in order to free the prisoners trapped inside."
   Modified 1710027248
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2BBBD7E0F}" {
   Id "PRTC-SC02_TaskHospital_Title"
   Target_en_us "Approach Hospital"
   Modified 1710027212
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C371647684}" {
   Id "PRTC-SC02_TaskWarCriminal_Text"
   Target_en_us "Find the unarmed FIA officer responsible for mistreating the civilians, and try to capture him."
   Modified 1710027117
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C33E82C2E5}" {
   Id "PRTC-SC02_TaskWarCriminal_Title"
   Target_en_us "Chase War Criminal (alternative)"
   Modified 1710027082
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65E852988CEB99FE}" {
   Id "PRTC-SC03_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This short but intense mission showcases:"\
   ""\
   "- Mass displacement of civilians as the safety of their home territory steadily degrades."\
   ""\
   "- Construction of mobile emergency response centers in order to redirect civilians away from the fighting zones."\
   ""\
   "Helicopter gunships will give you the edge when it comes to destroy the mortars which indiscriminately bomb the population, but beware of collateral damages."
   Modified 1709728219
   Author "mathi"
   LastChanged "mathi"
  }
  CustomStringTableItem "{65E85298E1880924}" {
   Id "PRTC-SC03_IntroHint_Title"
   Target_en_us "Protection - Showcase #3"
   Modified 1709727402
   Author "mathi"
   LastChanged "mathi"
  }
  CustomStringTableItem "{65ECE7CDC0127196}" {
   Id "PRTC-SC03_TaskEmergencyResponseCenter_Text"
   Target_en_us "Build an emergency response center away from the fighting zone, so that fleeing civilians can gather there."
   Modified 1710029755
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDD2CC2A74}" {
   Id "PRTC-SC03_TaskEmergencyResponseCenter_Title"
   Target_en_us "Build Emergency Response Center"
   Modified 1710029690
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CC7A1327E4}" {
   Id "PRTC-SC03_TaskGatherCivilians_Text"
   Target_en_us "Wait for enough civilians to gather at the response center. Depending on the situation, either defend or go looking for them."
   Modified 1710030366
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CC07307F1D}" {
   Id "PRTC-SC03_TaskGatherCivilians_Title"
   Target_en_us "Gather Civilians"
   Modified 1710030293
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CE4BB772AA}" {
   Id "PRTC-SC03_TaskNeutralizeMortar1_Title"
   Target_en_us "Neutralize Mortar Servant #1"
   Modified 1710029478
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDF0DC0235}" {
   Id "PRTC-SC03_TaskNeutralizeMortar2_Title"
   Target_en_us "Neutralize Mortar Servant #2"
   Modified 1710029625
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDEF4FF312}" {
   Id "PRTC-SC03_TaskNeutralizeMortar3_Title"
   Target_en_us "Neutralize Mortar Servant #3"
   Modified 1710029638
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDA4AA529F}" {
   Id "PRTC-SC03_TaskNeutralizeMortar_Text"
   Target_en_us "Neutralize the mortar servant, while avoiding collateral damages."
   Modified 1710029560
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CE03A7E56C}" {
   Id "PRTC-SC03_TaskRecon_Text"
   Target_en_us "The FIA seems to be moving mortars to Arlevile, take an helicopter and observe the situation from above."
   Modified 1710029401
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CE15DBDE6F}" {
   Id "PRTC-SC03_TaskRecon_Title"
   Target_en_us "Reconnaissance"
   Modified 1710029347
   Author "argeo"
   LastChanged "argeo"
  }
 }
}