StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65ECE7C2CC2DDBFE}" {
   Id "PRTC-Lore_Marker_BaseDefenders"
   Target_en_us "Base Defenders"
   Target_fr_fr "Défenseurs de la base"
   Modified 1710027408
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2381502C5}" {
   Id "PRTC-Lore_Marker_Patrols"
   Target_en_us "Patrols"
   Target_fr_fr "Patrouilles"
   Modified 1710027434
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C0B1CDE958}" {
   Id "PRTC-Lore_MissionStatus_CaptureWarCriminal_Partial"
   Target_en_us "Congratulations, you have captured the war criminal."
   Target_fr_fr "Félicitations, vous avez capturé le criminel de guerre."
   Modified 1710028150
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CB248EBFBC}" {
   Id "PRTC-Lore_MissionStatus_ProvideShelter_Defeat"
   Target_en_us "You were unable to provide shelter to enough civilians."
   Target_fr_fr "Vous n'avez pas pu fournir un abri à assez de civils."
   Modified 1710030960
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CD43FA87E4}" {
   Id "PRTC-Lore_MissionStatus_ProvideShelter_Victory"
   Target_en_us "Congratulations, you have provided with shelter the civilians fleeing the fighting."
   Target_fr_fr "Félicitations, vous avez fourni un abri aux civils fuyant les combats."
   Modified 1710920594
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C4A6EB1C67}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Defeat"
   Target_en_us "This is a disaster, no civilian was saved."
   Target_fr_fr "C'est un désastre, aucun civil n'a été sauvé."
   Modified 1710026090
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C5CA899496}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Draw"
   Target_en_us "Unfortunately, you could only save some civilians."
   Target_fr_fr "Malheureusement, vous n'avez pu sauver que certains civils."
   Modified 1710025781
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C5615B3F3A}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Partial"
   Target_en_us "Good job, you have saved many civilians."
   Target_fr_fr "Bon travail, vous avez sauvé nombreux civils."
   Modified 1710025963
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C54E5E38A9}" {
   Id "PRTC-Lore_MissionStatus_SaveCivilians_Victory"
   Target_en_us "Congratulations, you have saved most civilians!"
   Target_fr_fr "Félicitations, vous avez sauvé la plupart des civils !"
   Modified 1710026137
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C44EE48C32}" {
   Id "PRTC-Lore_Spawn_Approach"
   Target_en_us "Approach"
   Target_fr_fr "Approche"
   Modified 1710920612
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C3E3A49FDB}" {
   Id "PRTC-Lore_Spawn_Bunker"
   Target_en_us "Bunker"
   Target_fr_fr "Bunker"
   Modified 1710920616
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2FF9661C9}" {
   Id "PRTC-Lore_Spawn_Hospital"
   Target_en_us "Hospital"
   Target_fr_fr "Hôpital"
   Modified 1710027313
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C714DC30C3}" {
   Id "PRTC-Lore_Spawn_Hotel"
   Target_en_us "Hotel"
   Target_fr_fr "Hôtel"
   Modified 1710024951
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C7315FE9C2}" {
   Id "PRTC-Lore_Spawn_Insertion"
   Target_en_us "Insertion"
   Target_fr_fr "Insertion"
   Modified 1710024904
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C3BD6C239C}" {
   Id "PRTC-Lore_Spawn_MainBuilding"
   Target_en_us "Main Building"
   Target_fr_fr "Bâtiment principal"
   Modified 1710026484
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC148705644}" {
   Id "PRTC-SC01_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This short mission showcases:"\
   ""\
   "- The automated population of houses with civilians."\
   ""\
   "- The \"protection\" of AI non-combattants via their recruitment to commanded groups."\
   ""\
   "- Two additional civilian factions (Rural and Urban Civilians), which can be used to model populations of mixed ethnicity, social background, etc."\
   ""\
   "As confusion and misunderstandings reign, you have to focus on your mission to protect specific persons, while doing your best to prevent any war crime."
   Target_fr_fr "Les mods Protection étendent Arma Reforger avec les mécanismes du Droit International Humanitaire, également connu comme les \"lois de la guerre\".  Notamment, plus de comportements illicites sont punis que dans la version originale du jeu."\
   ""\
   "Cette mission courte met en évidence :"\
   ""\
   "- La population automatique des maisons par des civils."\
   ""\
   "- La \"protection\" des IAs non-combattantes via leur recrutement dans des groupes commandés."\
   ""\
   "- Deux factions civiles supplémentaires (civils Ruraux et Urbains), qui peuvent être utilisées pour modéliser des populations mixtes ethniquement, socialement, etc."\
   ""\
   "Alors que la confusion et les malentendus règnent, concentrez-vous sur votre mission qui consiste à protéger quelques personnes spécifiques, tout en faisant de votre mieux pour empêcher tout crime de guerre."
   Modified 1710920875
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC154C46AF7}" {
   Id "PRTC-SC01_IntroHint_Title"
   Target_en_us "Protection - Showcase #1"
   Target_fr_fr "Protection - Mission De Présentation N° 1"
   Modified 1710921100
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC36AAFBB60}" {
   Id "PRTC-SC01_Task01_Text"
   Target_en_us "Take a car and drive fast to Arleville in order to join urban businessmen meeting with the rural mayor."
   Target_fr_fr "Prenez une voiture et conduisez rapidement vers Arleville afin de rejoindre les businessmen Urbains en réunion avec le maire Rural d'Arleville."
   Modified 1710921174
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC49CAA44F1}" {
   Id "PRTC-SC01_Task01_Title"
   Target_en_us "Drive To Arleville"
   Target_fr_fr "Conduire Vers Arleville"
   Modified 1710921181
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C75859E049}" {
   Id "PRTC-SC01_Task02_Text"
   Target_en_us "Stay put and defend the businessmen until we understand what is going on."
   Target_fr_fr "Restez sur place et défendez les businessmen jusqu'à ce que nous comprenions mieux la situation."
   Modified 1710921218
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C77B207142}" {
   Id "PRTC-SC01_Task02_Title"
   Target_en_us "Defend The Businessmen"
   Target_fr_fr "Défendre Les Businessmen"
   Modified 1710921228
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C61ECD1FDD}" {
   Id "PRTC-SC01_Task03_Text"
   Target_en_us "Enraged FIA soldiers are arriving to protect the rural civilians. Avoid them and extract the surviving businessmen to Beauregard."
   Target_fr_fr "Des soldats FIA enragés de colère arrivent pour protéger les civils Ruraux. Évitez-les et assurez l'extraction les businessmen survivants vers Beauregard."
   Modified 1710921261
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C6C389BC1E}" {
   Id "PRTC-SC01_Task03_Title"
   Target_en_us "Flee With A Vehicle To Beauregard"
   Target_fr_fr "Fuir Avec Un Véhicule Vers Beauregard"
   Modified 1710921275
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65F4CB6EAD358314}" {
   Id "PRTC-SC02_AssaultTrigger_Text"
   Target_en_us "Rogue ОМСДОН troops will soon attack the base. Their past behavior indicates that the jailed civilians are in mortal danger."
   Target_fr_fr "Les troupes criminelles ОМСДОН vont bientôt attaquer la base. Leur comportement passé indique que les civils prisonniers sont en danger de mort."
   Modified 1710921348
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65F4CB6D4124807B}" {
   Id "PRTC-SC02_AssaultTrigger_Title"
   Target_en_us "URGENT INTEL - THE FULL-SCALE INVASION OF ARLAND HAS BEGUN!"
   Target_fr_fr "INTEL URGENTE - L'INVASION TOTALE D'ARLAND A DÉBUTÉ !"
   Modified 1710921382
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65D2F2451AC8854B}" {
   Id "PRTC-SC02_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This more dynamic and complex mission showcases:"\
   ""\
   "- The \"protection\" of AI non-combattants via their recruitment to commanded groups, and the challenges with directing them under heavy fire."\
   ""\
   "- The capturing of unarmed enemies."\
   ""\
   "The goal is to save as many civilians as possible, unfortunately not all of them. You will probably have to leave some behind in order to save at least few..."
   Target_fr_fr "Les mods Protection étendent Arma Reforger avec les mécanismes du Droit International Humanitaire, également connu comme les \"lois de la guerre\".  Notamment, plus de comportements illicites sont punis que dans la version originale du jeu."\
   ""\
   "Cette mission plus dynamique et complexe met en évidence :"\
   ""\
   "- La \"protection\" des IA non-combattantes via leur recrutement dans des groupes commandés, et la difficulté à les diriger sous feu nourri."\
   ""\
   "- La capture d'ennemis désarmés."\
   ""\
   "L'objectif est de sauver autant de civils que possible, mais malheureusement pas tous. Vous devrez probablement en abandonner certains afin de pouvoir en sauver au moins quelques-uns..."
   Modified 1710921496
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65D2F25A955474FD}" {
   Id "PRTC-SC02_IntroHint_Title"
   Target_en_us "Protection - Showcase #2"
   Target_fr_fr "Protection - Mission De Présentation N° 2"
   Modified 1710921107
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C406FA72AC}" {
   Id "PRTC-SC02_TaskApproach_Text"
   Target_en_us "Approach the base from the south-east."
   Target_fr_fr "Approcher de la base depuis le sud-est."
   Modified 1710026362
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C4146E51E1}" {
   Id "PRTC-SC02_TaskApproach_Title"
   Target_en_us "Approach"
   Target_fr_fr "Approche"
   Modified 1710921520
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C38ED3660E}" {
   Id "PRTC-SC02_TaskBunker_Text"
   Target_en_us "Approach the bunker and try to free the prisoners inside."
   Target_fr_fr "Approcher du bunker et tenter de libérer les prisonniers à l'intérieur."
   Modified 1710026831
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C398209E7F}" {
   Id "PRTC-SC02_TaskBunker_Title"
   Target_en_us "Approach Bunker"
   Target_fr_fr "Approcher Du Bunker"
   Modified 1710921546
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C1225D2B39}" {
   Id "PRTC-SC02_TaskExtraction_Text"
   Target_en_us "Bring the civilans and/or the war criminal to the extraction point."
   Target_fr_fr "Amenez les civils et/ou le criminel de guerre au point d'extraction."
   Modified 1710027956
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C1C042FE4B}" {
   Id "PRTC-SC02_TaskExtraction_Title"
   Target_en_us "Extraction"
   Target_fr_fr "Extraction"
   Modified 1710027881
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2A903EA07}" {
   Id "PRTC-SC02_TaskHospital_Text"
   Target_en_us "Approach the hospital in order to free the prisoners trapped inside."
   Target_fr_fr "Approcher de l'hôpital afin de libérer les civils prisonniers à l'intérieur."
   Modified 1710921583
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C2BBBD7E0F}" {
   Id "PRTC-SC02_TaskHospital_Title"
   Target_en_us "Approach Hospital"
   Target_fr_fr "Approcher De L'Hôpital"
   Modified 1710921594
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C371647684}" {
   Id "PRTC-SC02_TaskWarCriminal_Text"
   Target_en_us "Find the unarmed FIA officer responsible for mistreating the civilians, and try to capture him."
   Target_fr_fr "Trouvez l'officier FIA désarmé responsable des mauvais traitements infligés aux civils, et tentez de le capturer."
   Modified 1710921627
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7C33E82C2E5}" {
   Id "PRTC-SC02_TaskWarCriminal_Title"
   Target_en_us "Chase War Criminal (alternative)"
   Target_fr_fr "Poursuivre Le Criminel De Guerre (alternative)"
   Modified 1710921644
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65E852988CEB99FE}" {
   Id "PRTC-SC03_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This short but intense mission showcases:"\
   ""\
   "- Mass displacement of civilians as the safety of their home territory steadily degrades."\
   ""\
   "- Construction of mobile emergency response centers in order to redirect civilians away from the fighting zones."\
   ""\
   "Helicopter gunships will give you the edge when it comes to destroy the mortars which indiscriminately bomb the population, but beware of collateral damages."
   Target_fr_fr "Les mods Protection étendent Arma Reforger avec les mécanismes du Droit International Humanitaire, également connu comme les \"lois de la guerre\".  Notamment, plus de comportements illicites sont punis que dans la version originale du jeu."\
   ""\
   "Cette mission courte mais intense met en évidence :"\
   ""\
   "- Le déplacement en masse de civils alors que la sécurité de leur territoire se dégrade progressivement."\
   ""\
   "- La construction de centres de réponse d'urgence mobiles, afin d'éloigner les civils des zones de combat."\
   ""\
   "Les helicoptères de combat vous donneront un avantage lors de la destruction des mortiers qui bombardent sans distinction la population, mais soyez prudent avec les dommages collatéraux."
   Modified 1710921871
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65E85298E1880924}" {
   Id "PRTC-SC03_IntroHint_Title"
   Target_en_us "Protection - Showcase #3"
   Target_fr_fr "Protection - Mission De Présentation N° 3"
   Modified 1710921117
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDC0127196}" {
   Id "PRTC-SC03_TaskEmergencyResponseCenter_Text"
   Target_en_us "Build an emergency response center away from the fighting zone, so that fleeing civilians can gather there."
   Target_fr_fr "Construisez un centre de réponse d'urgence en dehors de la zone de combat, afin que les civils en fuite puissent s'y rassembler."
   Modified 1710921851
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDD2CC2A74}" {
   Id "PRTC-SC03_TaskEmergencyResponseCenter_Title"
   Target_en_us "Build Emergency Response Center"
   Target_fr_fr "Construire Un Centre De Réponse D'Urgence"
   Modified 1710921834
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CC7A1327E4}" {
   Id "PRTC-SC03_TaskGatherCivilians_Text"
   Target_en_us "Wait for enough civilians to gather at the response center. Depending on the situation, either defend or go looking for them."
   Target_fr_fr "Attendez que suffisamment de civils se rassemblent au centre de réponse d'urgence. Selon la situation, soit défendez-les soit allez les chercher."
   Modified 1710921823
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CC07307F1D}" {
   Id "PRTC-SC03_TaskGatherCivilians_Title"
   Target_en_us "Gather Civilians"
   Target_fr_fr "Rassembler Les Civils"
   Modified 1710921884
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CE4BB772AA}" {
   Id "PRTC-SC03_TaskNeutralizeMortar1_Title"
   Target_en_us "Neutralize Mortar Servant #1"
   Target_fr_fr "Neutraliser Le Servant De Mortier N° 1"
   Modified 1710921947
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDF0DC0235}" {
   Id "PRTC-SC03_TaskNeutralizeMortar2_Title"
   Target_en_us "Neutralize Mortar Servant #2"
   Target_fr_fr "Neutraliser Le Servant De Mortier N° 2"
   Modified 1710921953
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDEF4FF312}" {
   Id "PRTC-SC03_TaskNeutralizeMortar3_Title"
   Target_en_us "Neutralize Mortar Servant #3"
   Target_fr_fr "Neutraliser Le Servant De Mortier N° 3"
   Modified 1710921959
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CDA4AA529F}" {
   Id "PRTC-SC03_TaskNeutralizeMortar_Text"
   Target_en_us "Neutralize the mortar servant, while avoiding collateral damages."
   Target_fr_fr "Neutraliez le servant de mortier tout en évitant les dommages collatéraux."
   Modified 1710921977
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CE03A7E56C}" {
   Id "PRTC-SC03_TaskRecon_Text"
   Target_en_us "The FIA seems to be moving mortars to Arlevile, take an helicopter and observe the situation from above."
   Target_fr_fr "Les FIA semblent transporter des mortiers vers Arleville. Prenez un hélicoptère et observez la situation depuis le ciel."
   Modified 1710922018
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65ECE7CE15DBDE6F}" {
   Id "PRTC-SC03_TaskRecon_Title"
   Target_en_us "Reconnaissance"
   Target_fr_fr "Reconnaissance"
   Modified 1710029347
   Author "argeo"
   LastChanged "argeo"
  }
 }
}