StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65CD0DC148705644}" {
   Id "PRTC-SC01_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This short mission showcases:"\
   ""\
   "- The automated population of houses with civilians."\
   ""\
   "- The \"protection\" of AI non-combattants via their recruitment to commanded groups."\
   ""\
   "- Two additional civilian factions (Rural and Urban Civilians), which can be used to model populations of mixed ethnicity, social background, etc."\
   ""\
   "As confusion and misunderstandings reign, you have to focus on your mission to protect specific persons, while doing your best to prevent any war crime."
   Modified 1708331764
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC154C46AF7}" {
   Id "PRTC-SC01_IntroHint_Title"
   Target_en_us "Protection - Showcase #1"
   Modified 1707943634
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC36AAFBB60}" {
   Id "PRTC-SC01_Task01_Text"
   Target_en_us "Take a car and drive fast to Arleville in order to join businessmen meeting with the mayor."
   Modified 1707943280
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC49CAA44F1}" {
   Id "PRTC-SC01_Task01_Title"
   Target_en_us "Drive To Arleville"
   Modified 1707943319
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65D2F2451AC8854B}" {
   Id "PRTC-SC02_IntroHint_Text"
   Target_en_us "The Protection mods extend Arma Reforger with the mechanisms of International Humanitarian Law (IHL), also known as the \"laws of war\".  Notably, more unlawful behaviors are punished than in the vanilla version."\
   ""\
   "This more dynamic and complex mission showcases:"\
   ""\
   "- The \"protection\" of AI non-combattants via their recruitment to commanded groups, and the challenges with directing them under heavy fire."\
   ""\
   "- The capturing of unarmed enemies."\
   ""\
   "The goal is to save as many civilians as possible, unfortunately not all of them. You will probably have to leave some behind in order to save at least few..."
   Modified 1708331290
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65D2F25A955474FD}" {
   Id "PRTC-SC02_IntroHint_Title"
   Target_en_us "Protection - Showcase #2"
   Modified 1708331814
   Author "argeo"
   LastChanged "argeo"
  }
 }
}