SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{63230CF8232DF691}" {
     m_sEntityPrefab "{877128FBE22FF2C9}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_AP2K_OliveGreen_Sand_Stripes.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{63230CF803B34C47}" {
       m_eItemMode WEAPON
       m_iSupplyCost 8
      }
     }
    }
   }
  }
 }
}