SCR_FactionHomeTerritoryConfig {
 m_aFactionHomeTerritories {
  SCR_FactionHomeTerritory "{5AEEE58D17F8B088}" {
   m_iWeight 2
  }
  SCR_FactionHomeTerritory "{5AEEE58D17BAE314}" {
   m_iWeight 30
  }
 }
}