SCR_JournalSetupConfig {
 m_iJournalEntryToShowOnStart 0
 m_aJournals {
  SCR_JournalConfig "{626F0784CACF446F}" {
   m_FactionKey "US"
   m_aEntries {
    SCR_JournalEntry "{626F0784CACF4463}" {
     m_iEntryID 1
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SituationTitle"
     m_sEntryText "Apparently Soviet troops have suddenly appeared and attacked rural civilians. This was actually a diversion, which allowed them to take the heights in the middle of Arland."
    }
    SCR_JournalEntry "{626F0784CACF445C}" {
     m_iEntryID 2
     m_eJournalEntryType Mission
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_MissionTitle"
     m_sEntryText "You have to free hurt rural civilians which are prisoners of the FIA, before the Soviet troops attack them."
    }
    SCR_JournalEntry "{626F0784CACF445A}" {
     m_iEntryID 3
     m_eJournalEntryType Execution
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_ExecutionTitle"
     m_sEntryText "Equip with explosives (at least four) and a detonator, and enter the military base through the West, where there are holes in the fence and the wall."
    }
    SCR_JournalEntry "{626F0784CACF445B}" {
     m_iEntryID 4
     m_eJournalEntryType Signal
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SignalTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Signal_US"
    }
    SCR_JournalEntry "{626F0784CACF4458}" {
     m_iEntryID 5
     m_eJournalEntryType Intel
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_IntelTitle"
     m_sEntryText "Watch for patrols in the woods to the West of the base."
    }
   }
  }
 }
}