SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{60F0FA299AF8FF6F}" {
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{60F0FA265607624B}" {
   m_LabelGroupType FACTION
  }
 }
}